<?php

try {
    throw new RuntimeException();
} catch (Exception $foo) {

}
